#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
# Script to control prefered apps to launch for all themes
# Author: z0mbi3
# url:    https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/eww"

case "$1" in
    --menu)
        rofi -show drun -theme "$HOME"/.config/bspwm/src/rofi-themes/Launcher.rasi 
        ;;
    --rice)
        RiceSelector
        ;;
    --terminal)
        Term --terminal
        ;;
    --floating)
        Term --floating
        ;;
    --update)
        Term --update 
        ;;
    --checkupdates)
        Term --checkupdates
        ;;
    --netmanager)
		NetManagerDM
		;;
	--bluetooth)
		rofi-bluetooth
		;;
	--clipboard)
		rofi -modi "clipboard:greenclip print" -theme "$HOME"/.config/bspwm/src/rofi-themes/Clipboard.rasi -show clipboard -run-command '{cmd}'
		;;
	--screenshot)
		ScreenShoTer
		;;
	--powermenu)
        PowerMenu
        ;;
    --android)
		AndroidMount
		;;
    --ranger)
        Term --ranger
        ;;
    --nvim)
        Term --nvim
        ;;
    --music)
        Term --music
        ;;
    --fetch)
        Term --fetch
        ;;
        # Apps
    --filemanager)
        thunar
        ;;
    --browser)
        firefox
        ;;
    --editor)
        nvim
        ;;
    --telegram)
        telegram-desktop
        ;;
    --whats)
        whatsdesk --disable-gpu
        ;;
    --soundcontrol)
        pavucontrol
        ;;
    --note)
        obsidian
        ;;
        # Eww Widgets
    --KeyHelp)
	eww -c "$HOME/.config/bspwm/eww" open --toggle csheet
	;;
    --usercard)
        eww -c "$HOME/.config/bspwm/eww" open --toggle launchermenu
        ;;
    --player)
        eww -c "$HOME/.config/bspwm/eww" open --toggle music
        ;;
    --calendar)
        eww -c "$HOME/.config/bspwm/eww" open --toggle date
        ;;
    *)
        echo "Invalid Option"
        ;;
esac
